# ===================================================================================================
# Configuración Spring Boot - DEV
#
# Configuración para el profile de Spring "dev".
# Aquí se establece la configuración necesaria para el perfil de ejecución local con
# base de datos también local
# ===================================================================================================

# ===================================================================================================
# Propiedades estandar de Spring.
# Referencia completa en:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================================================

server:
  port: 8080

spring:
  profiles:
    active: dev
    include: swagger
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/admin_escolar
    username: root
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
    tomcat:
      max-active: 1

cxf:
  path: /soap-api